version: '2'
services:
    db:
        build: ./mysql
        hostname: api-db
        command: --default-authentication-plugin=mysql_native_password
        #restart: "no"
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: api
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: api
        volumes:
            - db_data:/var/lib/mysql
            - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    api:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "9000:8080"
        links:
            - db
        volumes:
            - ./api:/api
        command: go run /api/main.go

volumes:
    db_data:
